---
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/localdb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties.hibernate.format_sql: true

  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password: password
      timeout: 60000

  mail:
    host: smtp.yandex.ru
    username: polwen@yandex.ru
    password: ojqaiddvfalxmjzo
    port: 465
    protocol: smtps
mail:
  debug: true

logging:
  level:
    org.springframework.data.*.*: trace
    org.springframework.cache.*: trace